### PR TITLE
Adds == to Point

### PR DESCRIPTION
**Pull request by casper91**

### CODE REVIEW

**Comment by lrz** [comment]
I'm wondering if we shouldn't use `==` for this? Or perhaps add it as an alias?

**Comment by casper91** [comment]
I thought about it as well and wasn't sure because then you can't use `==` to check if the `Objects` are the same.

```Ruby
# Using equal?
p1 = MG::Point.new([0,0])
p2 = p1
p1 == p2 # yield true because it's the same object.
p2 =  MG::Point.new([0,0])
p1 == p2 # yield false because not same object.

# Using ==
p1 = MG::Point.new([0,0])
p2 = p1
p1 == p2 # yield true because it has same coordinates
p2 =  MG::Point.new([0,0])
p1 == p2 # yield true because it has same coordinates
```

But then again I'm not sure if someone would use `==` to check if the objects are the same?
So I think it is up to you to decide what you like :)

**Comment by lrz** [comment]
Shouldn't this be the opposite? 

```
irb(main):010:0> s = "foo"
=> "foo"
irb(main):011:0> s == s.dup
=> true
irb(main):012:0> s.equal?(s)
=> true
irb(main):013:0> s.equal?(s.dup)
=> false
irb(main):014:0> s == s
=> true
```

I think that `==` it used to compare the content of objects and `equal?` used to compare references? I am under cold medication at the moment so I may be wrong :)

**Comment by casper91** [comment]
I think you are right :)
```
Equality — At the Object level, == returns true only if obj and other are the same object. 
Typically, this method is overridden in descendant classes to provide class-specific meaning.

Unlike ==, the equal? method should never be overridden by subclasses 
as it is used to determine object identity (that is, a.equal?(b) if and only if a is the same object as b):
```
I will change it to use `==` and not override `equal?`

**Comment by lrz** [comment]
Thanks so much for the patch :)

**Pull request merged**
