### PR TITLE
removed hard coded path to `/usr/bin`

### PR DESCRIPTION
**Pull request by amirrajan**
My ruby version located at `/usr/bin` is version 2.0.0p648. With regards
to `rake gem`, the build would error on `spec.date = Date.today` (it
wouldn't find the date class). From what I can tell, `rake gem` requires
2.3.1p122 along with `require 'date'` at the top of the gemspec file so
that `Date#today` is available. With these changes, `rake gem` works if
you've got your ruby set up using rbenv.

### CODE REVIEW

**Comment by Watson1978** [comment]
If you saw this error, I think it is a problem in RubyGem.
Which RubyGem version have you used?

```
[~]$ rbenv shell system
[~]$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
[~]$ gem -v
2.0.14.1
```

**Comment by amirrajan** [comment]
Hmm... same as yours.

```
┌── [ ~/Projects  ]
└─» ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
┌── [ ~/Projects  ]
└─» gem -v
2.0.14.1
```

Let me see if I can reproduce this before you merge this in.

**Comment by amirrajan** [comment]
What do you get when you run:

```
┌── [ ~/Projects  ]
└─» /usr/bin/ruby  --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

**Comment by Watson1978** [comment]
I didn't find a reason of your problem yet.
However, I think your problem will be fixed with https://github.com/HipByte/motion-game/commit/5a6ebc9f8d3a05654cfe9322a7d02372e058b15c .

If you have a time, could you please confirm that ? 
Thank you.

**Comment by amirrajan** [comment]
confirmed. pull request not needed.

**Pull request closed without merging**
