### PR TITLE
added Button#load_texture_normal

### PR DESCRIPTION
**Pull request by amirrajan**

### CODE REVIEW

**Comment by eichert12** [comment]
I was considering a similar update.  What do you think about matching the cocos2d API and allowing normal, pressed, and disabled textures to all be supported?  I like the idea of having a constructor that accepts all 3 as well as a matching load_textures method.  Thoughts?

http://cocos2d-x.org/docs/programmers-guide/ui_components/#buttons
http://www.cocos2d-x.org/wiki/Overview_of_new_gui

**Comment by amirrajan** [comment]
Definitely, created an issue for it: https://github.com/HipByte/motion-game/issues/41

**Comment by amirrajan** [comment]
I'll do a separate pull request for that one (once I need the method :-D)

**Comment by eichert12** [comment]
Cool, I'll give a holler if I end up needing it first :)

**Comment by Watson1978** [comment]
Thanks!

**Pull request merged**
