### PR TITLE
Adds +:forever+ symbol to schedule

### PR DESCRIPTION
**Pull request by casper91**
Now possible to use `:forever` in schedule.
```Ruby
class UpdateExample < MG::Scene
  def initialize
    schedule(0, :forever, 5) { |delta| puts delta }
  end
end
````
This will print 5, every 5th second, for as long as the scene is running

### CODE REVIEW

**Comment by Watson1978** [comment]
if 2nd argument take `Symbol` or `Integer`, I think it isn't easy to understand.
Actually, document is described
```
@param repeat [Integer]
```
but, it is not right for your patch.

```
@param repeat [Symbol, Integer]
```
is right.

if user passed negative value in 2nd argument, it is better that it will recognize as `forever`, I think.


```
module MG
  class  Scene
    # define constant
    REPEAT_FORVER = -1
  end
end

class UpdateExample < MG::Scene
  def initialize
    schedule(0, REPEAT_FORVER, 5) { |delta| puts delta }
  end
end
```

**Comment by casper91** [comment]
Hmm, I feel you. 

However I could not find anything about `forever` in the documentation and took a guess with `-1`. So that should maybe be added?

Animation allow us to use symbol `:forever` as repeat. That is actually the reason for this patch.
https://github.com/HipByte/motion-game/blob/3f3325964bb6baf78e1887ec00b5ae6f198d8a8c/src/sprite.cpp#L160

**Comment by Watson1978** [comment]
> Animation allow us to use symbol :forever as loop. This is actually the reason for this patch.
> https://github.com/HipByte/motion-game/blob/3f3325964bb6baf78e1887ec00b5ae6f198d8a8c/src/sprite.cpp#L160

Nice found. I don't like its API.

**Comment by Watson1978** [comment]
Filed in #64

**Pull request closed without merging**
