### PR TITLE
Add support for additional Cocos2d actions

### LINKED ISSUE #47: Support for additional Cocos2d Actions
Currently only move_to, move_by, blink, and animate actions are available.  Within Cocos2d there are a lot of additional actions that would be useful to have access to in motion-game.

RotateTo/RotateBy
JumpTo/JumpBy
ScaleTo/ScaleBy
Sequence
Fade
Skew
Tint
Ease
etc.

I've created a branch to start adding additional actions, however, would benefit from everyone's thoughts on the API.  Currently the actions are available via methods on Sprite (which run the action immediately).  Ideally I'd like the ability to combine actions so would suggest an API off of sprite that makes running common actions easy (like we currently have for move_to/move_by), as well as an API that allows us to build up and combine actions.

Any thoughts or opinions?

http://www.cocos2d-x.org/wiki/Actions

### PR DESCRIPTION
**Pull request by eichert12**
Fixes #47 by adding additional motion-game classes for the various Cocos2d actions and adds Node#run_action.  I've kept the move_to/move_by, blink, and animate actions on Sprite (for now).  Give how common they are it may make sense to keep them as quick ways to run those common actions.  If they are going to stay we should be able to refactor the code a bit to remove the duplicate logic in actions.cpp and sprite.cpp for move_to/move_by, blink, and animate.

### CODE REVIEW

**Comment by eichert12** [comment]
Add the following to a scene to get a sense for the various actions available....

@label = MG::Text.new("Hello World", "Arial", 96)
    @label.anchor_point = [0, 0]
    @label.touch_enabled = true
    @label.on_touch do
      puts "Label Touch"
      @label.text_color = [255, 0, 0, 1.0]

      @label.run_action MG::MoveBy.new([100, 100], 1.0) do
        actions = [
                  MG::RotateBy.new(45, 1.0),
                  MG::RotateTo.new(0, 1.0),
                  MG::JumpBy.new([100, 100], 10, 5, 1.0),
                  MG::JumpTo.new([200, 200], 10, 5, 1.0),
                  MG::ScaleBy.new(2, 1.0),
                  MG::ScaleTo.new(0.5, 1.0),
                  MG::ScaleTo.new(1.0, 1.0),
                  MG::SkewBy.new(45, 90, 1.0),
                  MG::SkewTo.new(0, 0, 1.0),
                  MG::FadeOut.new(1.0),
                  MG::FadeIn.new(1.0),
                  MG::FadeTo.new(0.5, 1.0),
                  MG::FadeTo.new(1.0, 1.0),
                  MG::TintBy.new(0, 255, 0, 1.0),
                  MG::TintTo.new(0, 0, 255, 1.0),
                  MG::DelayTime.new(2.0),
                  MG::MoveTo.new([100, 100], 1.0),
                  MG::DelayTime.new(1.0)
                ]
        
        @label.text_color = [255, 255, 255, 1.0]
        @label.run_action MG::Sequence.new(actions)
      end

      true
    end
    add @label

**Comment by andrewhavens** [comment]
Nice work @eichert12! I had some thoughts on the API. Personally, I really like the "short cut" methods (i.e. `sprite.move_to([x,y], t`, etc). I definitely think that the actions should be namespaced under their own module like `MG::Actions` to keep them organized, but maybe having them aliased with short-cut methods to reduce the amount of typing.

What do you think about something like this?

```ruby
# the verbose way
action1 = MG::Actions::MoveBy.new([100, 100], 1.0)
action2 = MG::Actions::RotateBy.new(45, 1.0)
action3 = MG::Actions::JumpBy.new([100, 100], 10, 5, 1.0)
@label.run_sequence(action1, action2, action3)

# slightly less verbose
@label.run_sequence([
  MG::Action.moveBy([100, 100], 1.0),
  MG::Action.rotateBy(45, 1.0),
  MG::Action.jumpBy([100, 100], 10, 5, 1.0)
])


# maybe MG::Scene has these short-cuts to avoid typing MG::Action?
@label.run_sequence([
  moveBy([100, 100], 1.0),
  rotateBy(45, 1.0),
  jumpBy([100, 100], 10, 5, 1.0)
])

# without a sequence
@label.moveBy([100, 100], 1.0)
@label.rotateBy(45, 1.0)
@label.jumpBy([100, 100], 10, 5, 1.0)
```

**Comment by amirrajan** [comment]
Is this current version good enough? Maybe another pull request for the clean up? Maybe this would be a good helper

```
@label.run_sequence do |a|
  a.moveBy()
  a.rotateBy()
  a.jumpBy()
end

**Comment by amirrajan** [comment]
As an aside. I'm thinking it may be best to keep motion-games bridge as close to the Cocos2dx api and then build a "nice" layer as pure Ruby classes. Thoughts on this?

**Comment by eichert12** [comment]
I've been hesitant to put a "nice" ruby dsl layer on top of this since I haven't been actively using it and thus don't know what would be the best API to expose.  I have thought about creating a Ruby layer on top of the C extension as Amir proposed above and think it would provide a number of benefits.

**Comment by amirrajan** [comment]
I've been hesitant to put a "nice" ruby dsl layer on top of this since I haven't been actively using it and thus don't know what would be the best API to expose.

Same here. I'll probably make all the functions snake cased, but outside of that my modus operandi will be to expose methods verbatim (or as close as possible).

**Comment by andrewhavens** [comment]
I mostly agree. I think the first step should be to expose the cocos2d API as close as possible, where it makes sense, but then add additional helper/shortcut methods to simplify the code. One example of where I don't think it makes sense is how cocos2d doesn't namespace the actions (i.e. `RotateBy` would become `MG::RotateBy`). However, I think this would pollute the top-level `MG` namespace, so in this case, I propose that we nest the actions under a `MG::Actions` namespace.

```ruby
@label.run_action(MG::Actions::MoveBy.new([100, 100], 1.0))
```

Alternatively, since there isn't really anything you can do to modify an action after it has been instantiated, I think it makes sense to just make these class methods on an `MG::Action` class:

```ruby
@label.run_action(MG::Action.move_by([100, 100], 1.0))
```

I really like @amirrajan's suggestion for providing a block argument in `run_sequence`:

```ruby
@label.run_sequence do |s|
  s.move_by([100, 100], 1.0)
  s.rotate_by(45, 1.0)
  s.jump_by([100, 100], 10, 5, 1.0)
end
```

**Comment by amirrajan** [comment]
>One example of where I don't think it makes sense is how cocos2d doesn't namespace the actions (i.e. RotateBy would become MG::RotateBy)

I may be mistaken, but I think you can do:

```
class SomeClass
  Rotate = MG::RotateBy

end
```

>I think it makes sense to just make these class methods on an MG::Action class

It's a toss up for me. I want to be able to look at Cocos2dx docs and have it "just work". But at the same time, I like some of the shortcuts (such as a tuple for location).

**Comment by amirrajan** [comment]
@Watson1978 I think this is ready to merge in.

**Comment by andrewhavens** [comment]
@amirrajan I support the idea of merging this as-is to start to get this functionality in here. However, I think we should still consider a "phase 2" which adds the "nice Ruby DSL layer".

In regards to aliasing the action classes like this:

```ruby
class SomeClass
  Rotate = MG::RotateBy
end
```

...my concern is with organization and documentation. For example, if you look at the [current API documentation](http://www.rubymotion.com/developers/motion-game/_index.html), you can see that there is a relatively simple set of top level objects/building blocks for working with motion-game. `MG::Events` is a module which includes several types of events and [the documentation keeps them organized](http://www.rubymotion.com/developers/motion-game/MG/Events.html). I like this approach as a way of organizing these classes, not only the documentation, but also the API that we would use to find an action.

**Comment by amirrajan** [comment]
>I support the idea of merging this as-is to start to get this functionality in here. However, I think we should still consider a "phase 2" which adds the "nice Ruby DSL layer".

Hard for me to say what the nice Ruby DSL layer would like (I'm sure there would be many opinions there). I've got two code bases that I'm trying to convert to "vanilla" motion-game. One is 1.600 lines of SpriteKit, the other is 7,000 lines (gasp).

**Comment by amirrajan** [comment]
Just musing on this a bit more. I could see having multiple "nice Ruby DSL layer" templates that cater to different types of games:

- `motion create SaveThePrincess template=motion-game-2d-scroller`
- `motion create DanceDanceFingers template=motion-game-rhythm`
- `motion create DragonSlayer template=motion-game-rpg`

Each providing their own "opinions" that cater to each genre.

**Comment by andrewhavens** [comment]
@amirrajan That's definitely a concept/feature I've been wanting to introduce in whatever game framework I'm committing to (started working on my own for a while but it's now at the end of my todo list). It seems like there are a lot of common boilerplate functionality for each type of game. Mostly things like perspective (side-scroller, bird's-eye-view, etc) which, I was thinking, could be a type of scene that you extend from. There are certainly a lot of helpful DSLs we could create once we have a fully-featured framework to use. =]

**Comment by andrewhavens** [comment]
@Watson1978 @lrz Can you please review this PR and merge if you think it's ready? It would be nice to get some of these motion-game PRs merged too.

**Pull request merged**
